### ISSUE TITLE
The docs badge on readme is broken

### ISSUE THREAD

**Issue by SebastianM-C** [SciML/SciMLStructures.jl#10]
**Describe the bug 🐞**

Clicking on the badge in the readme leads to https://docs.sciml.ai/SciMLStructures/stable/, which returns a 403 error
 
![image](https://github.com/SciML/SciMLStructures.jl/assets/31181429/4417536f-e2ab-41a5-8a6b-112196cf58a9)

**Expected behavior**

Working link.

Additionally the latest docs deploy link is https://sciml.github.io/SciMLStructures.jl/dev/, which gives a 404, so the docs preview link on PRs might also be broken.

**Comment by ChrisRackauckas** [comment]
Should be fixed with the new docs build.
